### ISSUE TITLE
DjangoUnicodeEncodeError when trying to get data from database

### ISSUE THREAD

**Issue by jekku0966** [alexmorozov/templated-docs#5]
* Templated-docs version: 0.2.9
* Python version: 3.5.2
* Operating System: Linux Mint 18 in VirtualBox 5.1.4

### Description

I'm getting DjangoUnicodeEncodeError for no apparrent reason.

Here's the error page code: ﻿http://dpaste.com/3QBF0F7

### What I Did

I'm trying to get some data from my database to a .pdf file for printing. I can't get this module to produce a pdf file at all. The django debug error site gives a hint for a .png and I can't locate any png files in my data request.

The only place I can find a mention for a png file is in the `__init__.py` file line 99.
`data = smart_str(source.read(name))` where a variable of `name` has a value of `Thumbnails/thumbnail.png` when the site is trying to produce the aforementioned file with the data I need.

**Comment by alexmorozov** [comment]
Honestly, I couldn't repoduce the issue on my machine, but I have a primary suspect. Can you please check whether a new version, 0.2.10, has fixed that behaviour?

**Comment by jekku0966** [comment]
Sorry not answering sooner.
Version 0.2.10 fixed the issue and is working like a charm!

Thank you!
