### ISSUE TITLE
Template generation hangs after first request

### ISSUE THREAD

**Issue by civantos** [alexmorozov/templated-docs#6]
* Templated-docs version: templated-docs==0.2.10
* Python version: 2.7.9
* Operating System: Debian 8.0
* Django version: 1.9.10
* LibreOffice version: 4.3.3.2 430m0(Build:2)

### Description

I'm trying to use a base case example filling a receipt with data from my database in a Django App.
Everything seems to be working as expected, no errors in the Django development server nor requests, but I only get the file the first time that I make the GET request to the method that I'm using to generate de DOCX file with my data. Then if I call this method for second time and so on, the GET remains waiting for a response from server that nevers is produced.

It's sounds to me like if the first request is not ending correctly de libreoffice proccess being used to generate the template output, but I'm just guessing.

DEBUG SERVER SAMPLE OUTPUT:

```
Django version 1.9.10, using settings 'extrematic.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
create libreoffice object
Uno initialized 1
initialized
[29/Sep/2016 14:13:36] "GET /expediente/398/solicitud_pago/ HTTP/1.1" 200 62645
create libreoffice object
```

METHOD THAT I'M USING TO PASS DATA TO TEMPLATE:

```
@csrf_exempt
@staff_member_required
@require_http_methods(["GET",])
def solicitud_pago(request, expediente):
  expediente = Expediente.objects.get(pk=expediente)
  servicios = Servicio.objects.filter(expediente=expediente)
  context = {'user': request.user, 'expediente': expediente, 'servicios': servicios, 'fecha': datetime.date.today() }
  filename = fill_template('solicitud_pago.odt', context, output_format='docx')
  visible_filename = 'solicitud_pago.docx'
  return FileResponse(filename, visible_filename)
```

Thanks in advance for your help and for all the effort building this app.

Regards,

Javier Civantos

**Comment by alexmorozov** [comment]
Hi Javier, thanks for the thorough report! I believe that is the same bug @dukeimg once spotted in #3. I've just pushed the 0.3.0 version to PyPi, please check if it solves your problem.

**Comment by civantos** [comment]
I've setting up an VM with the same settings and the problem was still there. Then I updated to V 0.3.0 from PyPi and now It seems to be working properly :+1: 

Thank You so much for taking the time to solve this so quickly.

Regards,

Javier Civantos

**Comment by alexmorozov** [comment]
Javier, I'm glad to hear that everything works now. Closing this.
