### ISSUE TITLE
Generates corrupted file

### ISSUE THREAD

**Issue by hmilkovi** [alexmorozov/templated-docs#8]
* Templated-docs version: 0.3.1
* Python version: 2.7.10
* Operating System: OSX 10.12

### Description

When i generate odt from odt template that is filled with data i get
corrupted file libreoffice says:
Read-Error.
Format error discovered in the file in sub-document content.xml at 2,199655(row,col).

**Comment by alexmorozov** [comment]
Hi Hrvoje, thanks for a report. Could you share a file that crashes the library? I have some suspects to cause the behavior, but I'd like to double-check.

**Comment by hmilkovi** [comment]
Could you provide you email on which you want the file.
I don't like to share files to public that are from a client just filled with my template tags

**Comment by alexmorozov** [comment]
Sure, send the template and a sample context to inductor2000@mail.ru

Regards,
Alex Morozov

**Comment by alexmorozov** [comment]
@hmilkovi , have you managed to resolve your issue? If you have, please share what you did. If not, send the non-working template to inductor2000@mail.ru.
Thanks!

**Comment by alexmorozov** [comment]
Closing this due to the lack of activity. Feel free to reopen.
